version: '3.7'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=production_2024.settings
      - SECRET_KEY=django-insecure-ey+vweu#^u6jin-d4p0&7*%)w!^qkoz1hh&v*y@$oy(q3*b((w
      - DEBUG=False
      - ALLOWED_HOSTS=ephor.com.br,localhost,127.0.0.1
      - CSRF_TRUSTED_ORIGINS=https://ephor.com.br:443
      - CSRF_COOKIE_SECURE=True
      - SECURE_SSL_REDIRECT=True
      - SESSION_COOKIE_SECURE=True
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=secure_password
      - DB_HOST=db
      - DB_PORT=3306  # Django se conecta à porta padrão do MySQL dentro do contêiner
    networks:
      - ephor-network
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        labels: "production_2024_logs"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - django
    container_name: nginx
    networks:
      - ephor-network

  db:
    image: mysql:8.0  # Alterado para MySQL 8.0 para compatibilidade com Django
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: secure_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"  # Porta externa 3307 mapeada para a porta MySQL interna 3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ephor-network

volumes:
  static:
  media:
  db_data:

networks:
  ephor-network:
    driver: bridge
