version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    ports:
      - "8081:8080"  # Porta externa 8081 para acessar o container Django na porta 8080
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=production_2024.settings
      - SECRET_KEY=django-insecure-ey+vweu#^u6jin-d4p0&7*%)w!^qkoz1hh&v*y@$oy(q3*b((w
      - DEBUG=False
      - ALLOWED_HOSTS=ephor.com.br,localhost,127.0.0.1,192.168.0.10,172.30.0.3
      - CSRF_TRUSTED_ORIGINS=https://ephor.com.br
      - CSRF_COOKIE_SECURE=True
      - SECURE_SSL_REDIRECT=True
      - SESSION_COOKIE_SECURE=True
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=secure_password
      - DB_HOST=db
      - DB_PORT=3306
    networks:
      ephor-network:
        ipv4_address: 172.30.0.3
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        labels: "production_2024_logs"

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: secure_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      ephor-network:
        ipv4_address: 172.30.0.2

volumes:
  static:
  media:
  db_data:

networks:
  ephor-network:
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.30.0.0/16
